export const standardFormFieldRegistry = {
	button: ['disabled', 'form', 'name', 'autocomplete', 'value', 'readonly', 'required'],
	checkbox: ['disabled', 'form', 'name', 'value', 'required', 'checked', 'list'],
	color: ['disabled', 'form', 'name', 'autocomplete', 'value'],
	date: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'max',
		'min',
		'step'
	],
	'datetime-local': [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'max',
		'min',
		'step'
	],
	email: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'maxlength',
		'minlength',
		'multiple',
		'pattern',
		'size'
	],
	file: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'accept',
		'capture',
		'multiple'
	],
	hidden: ['disabled', 'form', 'name', 'autocomplete', 'value', 'list'],
	image: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'readonly',
		'required',
		'alt',
		'formaction',
		'formenctype',
		'formmethod',
		'formnovalidate',
		'formtarget',
		'height',
		'src',
		'width'
	],
	month: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'max',
		'min',
		'step'
	],
	number: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'max',
		'min',
		'pattern',
		'step'
	],
	password: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'maxlength',
		'list',
		'minlength',
		'pattern',
		'size'
	],
	radio: ['disabled', 'form', 'name', 'value', 'required', 'checked', 'list'],
	range: ['disabled', 'form', 'name', 'autocomplete', 'value', 'max', 'min', 'step'],
	reset: ['disabled', 'form', 'name', 'autocomplete', 'value', 'readonly', 'required'],
	search: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'maxlength',
		'dirname',
		'minlength',
		'pattern',
		'size'
	],
	submit: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'formaction',
		'formenctype',
		'formmethod',
		'formnovalidate',
		'formtarget'
	],
	tel: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'maxlength',
		'minlength',
		'pattern',
		'size'
	],
	text: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'maxlength',
		'dirname',
		'minlength',
		'pattern',
		'size'
	],
	time: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'max',
		'min',
		'step'
	],
	url: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'maxlength',
		'minlength',
		'pattern',
		'size'
	],
	week: [
		'disabled',
		'form',
		'name',
		'autocomplete',
		'value',
		'readonly',
		'required',
		'max',
		'min',
		'step'
	]
};

